"""
Supplementary curated movies catalog — Bollywood, South Indian & modern Hollywood.
These movies are injected alongside MovieLens data.
IDs start at 1,000,000 to avoid collisions with MovieLens IDs.
Genres use the same pipe-delimited format as MovieLens.
"""

CUSTOM_MOVIES = [
    # ── Bollywood / Hindi (60 movies) ────────────────────────────────────────
    {"movieId": 1000001, "title": "3 Idiots (2009)",                  "genres": "Comedy|Drama",                  "region": "Bollywood"},
    {"movieId": 1000002, "title": "Dangal (2016)",                    "genres": "Drama|Sport",                    "region": "Bollywood"},
    {"movieId": 1000003, "title": "PK (2014)",                        "genres": "Comedy|Drama|Sci-Fi",            "region": "Bollywood"},
    {"movieId": 1000004, "title": "Lagaan (2001)",                    "genres": "Drama|Sport",                    "region": "Bollywood"},
    {"movieId": 1000005, "title": "Barfi! (2012)",                    "genres": "Comedy|Drama|Romance",           "region": "Bollywood"},
    {"movieId": 1000006, "title": "Dil Chahta Hai (2001)",            "genres": "Comedy|Drama|Romance",           "region": "Bollywood"},
    {"movieId": 1000007, "title": "Zindagi Na Milegi Dobara (2011)",  "genres": "Adventure|Comedy|Drama",         "region": "Bollywood"},
    {"movieId": 1000008, "title": "Taare Zameen Par (2007)",          "genres": "Drama",                         "region": "Bollywood"},
    {"movieId": 1000009, "title": "Queen (2014)",                     "genres": "Drama|Romance",                  "region": "Bollywood"},
    {"movieId": 1000010, "title": "Andhadhun (2018)",                 "genres": "Crime|Mystery|Thriller",         "region": "Bollywood"},
    {"movieId": 1000011, "title": "Gangs of Wasseypur (2012)",        "genres": "Action|Crime|Drama",             "region": "Bollywood"},
    {"movieId": 1000012, "title": "Drishyam (2015)",                  "genres": "Crime|Drama|Mystery|Thriller",   "region": "Bollywood"},
    {"movieId": 1000013, "title": "KB (Kabir Singh) (2019)",          "genres": "Drama|Romance",                  "region": "Bollywood"},
    {"movieId": 1000014, "title": "War (2019)",                       "genres": "Action|Thriller",                "region": "Bollywood"},
    {"movieId": 1000015, "title": "Pathaan (2023)",                   "genres": "Action|Adventure|Thriller",      "region": "Bollywood"},
    {"movieId": 1000016, "title": "Jawan (2023)",                     "genres": "Action|Drama|Thriller",          "region": "Bollywood"},
    {"movieId": 1000017, "title": "Animal (2023)",                    "genres": "Action|Crime|Drama",             "region": "Bollywood"},
    {"movieId": 1000018, "title": "Tumbbad (2018)",                   "genres": "Fantasy|Horror|Mystery",         "region": "Bollywood"},
    {"movieId": 1000019, "title": "Article 15 (2019)",                "genres": "Crime|Drama|Mystery",            "region": "Bollywood"},
    {"movieId": 1000020, "title": "Shershaah (2021)",                 "genres": "Action|Biography|Drama|War",     "region": "Bollywood"},
    {"movieId": 1000021, "title": "83 (2021)",                        "genres": "Biography|Drama|Sport",          "region": "Bollywood"},
    {"movieId": 1000022, "title": "Brahmastra (2022)",                "genres": "Action|Adventure|Fantasy",       "region": "Bollywood"},
    {"movieId": 1000023, "title": "Kho Gaye Hum Kahan (2023)",        "genres": "Comedy|Drama|Romance",           "region": "Bollywood"},
    {"movieId": 1000024, "title": "Swades (2004)",                    "genres": "Drama|Romance",                  "region": "Bollywood"},
    {"movieId": 1000025, "title": "Band Baaja Baaraat (2010)",        "genres": "Comedy|Romance",                 "region": "Bollywood"},
    # New Bollywood additions
    {"movieId": 1000026, "title": "Rang De Basanti (2006)",           "genres": "Drama|Comedy",                   "region": "Bollywood"},
    {"movieId": 1000027, "title": "Bajrangi Bhaijaan (2015)",         "genres": "Adventure|Comedy|Drama",         "region": "Bollywood"},
    {"movieId": 1000028, "title": "Chhichhore (2019)",                "genres": "Comedy|Drama",                   "region": "Bollywood"},
    {"movieId": 1000029, "title": "Stree (2018)",                     "genres": "Comedy|Horror",                  "region": "Bollywood"},
    {"movieId": 1000030, "title": "Stree 2 (2024)",                   "genres": "Comedy|Horror",                  "region": "Bollywood"},
    {"movieId": 1000031, "title": "Bhool Bhulaiyaa (2007)",           "genres": "Comedy|Horror|Mystery",          "region": "Bollywood"},
    {"movieId": 1000032, "title": "Bhool Bhulaiyaa 2 (2022)",         "genres": "Comedy|Horror|Mystery",          "region": "Bollywood"},
    {"movieId": 1000033, "title": "Bhool Bhulaiyaa 3 (2024)",         "genres": "Comedy|Horror|Mystery",          "region": "Bollywood"},
    {"movieId": 1000034, "title": "Singham (2011)",                   "genres": "Action|Drama",                   "region": "Bollywood"},
    {"movieId": 1000035, "title": "Singham Returns (2014)",           "genres": "Action|Drama",                   "region": "Bollywood"},
    {"movieId": 1000036, "title": "Singham Again (2024)",             "genres": "Action|Drama",                   "region": "Bollywood"},
    {"movieId": 1000037, "title": "Golmaal (2006)",                   "genres": "Comedy",                         "region": "Bollywood"},
    {"movieId": 1000038, "title": "Hera Pheri (2000)",                "genres": "Comedy|Crime",                   "region": "Bollywood"},
    {"movieId": 1000039, "title": "Phir Hera Pheri (2006)",           "genres": "Comedy|Crime",                   "region": "Bollywood"},
    {"movieId": 1000040, "title": "Welcome (2007)",                   "genres": "Action|Comedy",                  "region": "Bollywood"},
    {"movieId": 1000041, "title": "Dhoom (2004)",                     "genres": "Action|Thriller",                "region": "Bollywood"},
    {"movieId": 1000042, "title": "Dhoom 2 (2006)",                   "genres": "Action|Adventure|Thriller",      "region": "Bollywood"},
    {"movieId": 1000043, "title": "Dhoom 3 (2013)",                   "genres": "Action|Thriller",                "region": "Bollywood"},
    {"movieId": 1000044, "title": "Raees (2017)",                     "genres": "Action|Crime|Drama",             "region": "Bollywood"},
    {"movieId": 1000045, "title": "Badlapur (2015)",                  "genres": "Crime|Drama|Thriller",           "region": "Bollywood"},
    {"movieId": 1000046, "title": "Piku (2015)",                      "genres": "Comedy|Drama",                   "region": "Bollywood"},
    {"movieId": 1000047, "title": "Gully Boy (2019)",                 "genres": "Drama|Music",                    "region": "Bollywood"},
    {"movieId": 1000048, "title": "Bhaag Milkha Bhaag (2013)",        "genres": "Biography|Drama|Sport",          "region": "Bollywood"},
    {"movieId": 1000049, "title": "Pad Man (2018)",                   "genres": "Biography|Comedy|Drama",         "region": "Bollywood"},
    {"movieId": 1000050, "title": "Toilet: Ek Prem Katha (2017)",     "genres": "Comedy|Drama|Romance",           "region": "Bollywood"},
    {"movieId": 1000051, "title": "Tanhaji (2020)",                   "genres": "Action|Drama|History",           "region": "Bollywood"},
    {"movieId": 1000052, "title": "Uri: The Surgical Strike (2019)",  "genres": "Action|Drama|War",               "region": "Bollywood"},
    {"movieId": 1000053, "title": "Raazi (2018)",                     "genres": "Drama|Thriller|War",             "region": "Bollywood"},
    {"movieId": 1000054, "title": "Neerja (2016)",                    "genres": "Biography|Drama|Thriller",       "region": "Bollywood"},
    {"movieId": 1000055, "title": "Rockstar (2011)",                  "genres": "Drama|Music|Romance",            "region": "Bollywood"},
    {"movieId": 1000056, "title": "Yeh Jawaani Hai Deewani (2013)",   "genres": "Comedy|Drama|Romance",           "region": "Bollywood"},
    {"movieId": 1000057, "title": "Ae Dil Hai Mushkil (2016)",        "genres": "Drama|Romance",                  "region": "Bollywood"},
    {"movieId": 1000058, "title": "Tamasha (2015)",                   "genres": "Drama|Romance",                  "region": "Bollywood"},
    {"movieId": 1000059, "title": "Drishyam 2 (2022)",                "genres": "Crime|Drama|Mystery|Thriller",   "region": "Bollywood"},
    {"movieId": 1000060, "title": "OMG – Oh My God! (2012)",          "genres": "Comedy|Drama",                   "region": "Bollywood"},

    # ── South Indian (60 movies) ─────────────────────────────────────────────
    {"movieId": 1000101, "title": "Baahubali: The Beginning (2015)",  "genres": "Action|Adventure|Fantasy|Drama", "region": "South Indian"},
    {"movieId": 1000102, "title": "Baahubali 2: The Conclusion (2017)","genres": "Action|Adventure|Fantasy|Drama","region": "South Indian"},
    {"movieId": 1000103, "title": "RRR (2022)",                       "genres": "Action|Adventure|Drama",         "region": "South Indian"},
    {"movieId": 1000104, "title": "KGF: Chapter 1 (2018)",            "genres": "Action|Crime|Drama",             "region": "South Indian"},
    {"movieId": 1000105, "title": "KGF: Chapter 2 (2022)",            "genres": "Action|Crime|Drama",             "region": "South Indian"},
    {"movieId": 1000106, "title": "Vikram (2022)",                    "genres": "Action|Crime|Thriller",          "region": "South Indian"},
    {"movieId": 1000107, "title": "Pushpa: The Rise (2021)",          "genres": "Action|Crime|Drama",             "region": "South Indian"},
    {"movieId": 1000108, "title": "Pushpa 2: The Rule (2024)",        "genres": "Action|Crime|Drama",             "region": "South Indian"},
    {"movieId": 1000109, "title": "Kantara (2022)",                   "genres": "Action|Drama|Mystery|Thriller",  "region": "South Indian"},
    {"movieId": 1000110, "title": "Varisu (2023)",                    "genres": "Action|Drama|Family",            "region": "South Indian"},
    {"movieId": 1000111, "title": "Dasara (2023)",                    "genres": "Action|Drama",                   "region": "South Indian"},
    {"movieId": 1000112, "title": "Leo (2023)",                       "genres": "Action|Crime|Thriller",          "region": "South Indian"},
    {"movieId": 1000113, "title": "Jailer (2023)",                    "genres": "Action|Comedy|Drama",            "region": "South Indian"},
    {"movieId": 1000114, "title": "Salaar (2023)",                    "genres": "Action|Crime|Drama",             "region": "South Indian"},
    {"movieId": 1000115, "title": "Maharaja (2024)",                  "genres": "Action|Crime|Thriller",          "region": "South Indian"},
    {"movieId": 1000116, "title": "Vikram Vedha (2022)",              "genres": "Action|Crime|Drama|Thriller",    "region": "South Indian"},
    {"movieId": 1000117, "title": "Soorarai Pottru (2020)",           "genres": "Biography|Drama",                "region": "South Indian"},
    {"movieId": 1000118, "title": "Jai Bhim (2021)",                  "genres": "Crime|Drama|Mystery",            "region": "South Indian"},
    {"movieId": 1000119, "title": "2.0 (2018)",                       "genres": "Action|Sci-Fi|Thriller",         "region": "South Indian"},
    {"movieId": 1000120, "title": "Kalki 2898 AD (2024)",             "genres": "Action|Adventure|Fantasy|Sci-Fi","region": "South Indian"},
    {"movieId": 1000121, "title": "Devara (2024)",                    "genres": "Action|Crime|Drama",             "region": "South Indian"},
    {"movieId": 1000122, "title": "Kanguva (2024)",                   "genres": "Action|Adventure|Fantasy",       "region": "South Indian"},
    {"movieId": 1000123, "title": "Nayakan (1987)",                   "genres": "Crime|Drama|Thriller",           "region": "South Indian"},
    {"movieId": 1000124, "title": "Drishyam 2 (2021)",                "genres": "Crime|Drama|Mystery|Thriller",   "region": "South Indian"},
    {"movieId": 1000125, "title": "Lucifer (2019)",                   "genres": "Action|Crime|Drama|Thriller",    "region": "South Indian"},
    # New South Indian additions
    {"movieId": 1000126, "title": "Master (2021)",                    "genres": "Action|Crime|Thriller",          "region": "South Indian"},
    {"movieId": 1000127, "title": "Beast (2022)",                     "genres": "Action|Comedy|Thriller",         "region": "South Indian"},
    {"movieId": 1000128, "title": "Ponniyin Selvan: I (2022)",        "genres": "Action|Adventure|Drama|History", "region": "South Indian"},
    {"movieId": 1000129, "title": "Ponniyin Selvan: II (2023)",       "genres": "Action|Adventure|Drama|History", "region": "South Indian"},
    {"movieId": 1000130, "title": "Super Deluxe (2019)",              "genres": "Comedy|Crime|Drama|Thriller",    "region": "South Indian"},
    {"movieId": 1000131, "title": "Asuran (2019)",                    "genres": "Action|Drama",                   "region": "South Indian"},
    {"movieId": 1000132, "title": "Kaithi (2019)",                    "genres": "Action|Thriller",                "region": "South Indian"},
    {"movieId": 1000133, "title": "Ratsasan (2018)",                  "genres": "Crime|Mystery|Thriller",         "region": "South Indian"},
    {"movieId": 1000134, "title": "96 (2018)",                        "genres": "Drama|Romance",                  "region": "South Indian"},
    {"movieId": 1000135, "title": "Premam (2015)",                    "genres": "Comedy|Drama|Romance",           "region": "South Indian"},
    {"movieId": 1000136, "title": "Drishyam (2013)",                  "genres": "Crime|Drama|Mystery|Thriller",   "region": "South Indian"},
    {"movieId": 1000137, "title": "Bangalore Days (2014)",            "genres": "Comedy|Drama|Romance",           "region": "South Indian"},
    {"movieId": 1000138, "title": "Charlie (2015)",                   "genres": "Adventure|Drama|Romance",        "region": "South Indian"},
    {"movieId": 1000139, "title": "Kumbalangi Nights (2019)",         "genres": "Comedy|Drama|Romance",           "region": "South Indian"},
    {"movieId": 1000140, "title": "Jallikattu (2019)",                "genres": "Action|Drama|Thriller",          "region": "South Indian"},
    {"movieId": 1000141, "title": "Minnal Murali (2021)",             "genres": "Action|Adventure|Comedy|Drama",  "region": "South Indian"},
    {"movieId": 1000142, "title": "Jana Gana Mana (2022)",            "genres": "Crime|Drama|Thriller",           "region": "South Indian"},
    {"movieId": 1000143, "title": "777 Charlie (2022)",               "genres": "Adventure|Comedy|Drama",         "region": "South Indian"},
    {"movieId": 1000144, "title": "Garuda Gamana Vrishabha Vahana (2021)", "genres": "Crime|Drama|Thriller",      "region": "South Indian"},
    {"movieId": 1000145, "title": "Ulidavaru Kandanthe (2014)",       "genres": "Crime|Drama|Thriller",           "region": "South Indian"},
    {"movieId": 1000146, "title": "Karnan (2021)",                    "genres": "Action|Drama",                   "region": "South Indian"},
    {"movieId": 1000147, "title": "Sarpatta Parambarai (2021)",       "genres": "Action|Drama|Sport",             "region": "South Indian"},
    {"movieId": 1000148, "title": "Vada Chennai (2018)",              "genres": "Action|Crime|Drama",             "region": "South Indian"},
    {"movieId": 1000149, "title": "Mahanati (2018)",                  "genres": "Biography|Drama|Romance",        "region": "South Indian"},
    {"movieId": 1000150, "title": "Eega (2012)",                      "genres": "Action|Comedy|Fantasy",          "region": "South Indian"},
    {"movieId": 1000151, "title": "Arjun Reddy (2017)",               "genres": "Drama|Romance",                  "region": "South Indian"},
    {"movieId": 1000152, "title": "Rangasthalam (2018)",              "genres": "Action|Drama",                   "region": "South Indian"},
    {"movieId": 1000153, "title": "Ala Vaikunthapurramuloo (2020)",   "genres": "Action|Comedy|Drama",            "region": "South Indian"},
    {"movieId": 1000154, "title": "Saaho (2019)",                     "genres": "Action|Thriller",                "region": "South Indian"},
    {"movieId": 1000155, "title": "The Greatest of All Time (2024)",  "genres": "Action|Sci-Fi|Thriller",         "region": "South Indian"},
    {"movieId": 1000156, "title": "Amaran (2024)",                    "genres": "Action|Biography|Drama|War",     "region": "South Indian"},
    {"movieId": 1000157, "title": "Lucky Bhaskar (2024)",             "genres": "Crime|Drama|Thriller",           "region": "South Indian"},
    {"movieId": 1000158, "title": "Meiyazhagan (2024)",               "genres": "Drama",                          "region": "South Indian"},
    {"movieId": 1000159, "title": "Viduthalai Part 1 (2023)",         "genres": "Action|Drama|Thriller",          "region": "South Indian"},
    {"movieId": 1000160, "title": "Lubber Pandhu (2024)",             "genres": "Drama|Sport",                    "region": "South Indian"},

    # ── Modern Hollywood (60 movies) ─────────────────────────────────────────
    {"movieId": 1000201, "title": "Avengers: Infinity War (2018)",    "genres": "Action|Adventure|Sci-Fi",       "region": "Hollywood"},
    {"movieId": 1000202, "title": "Avengers: Endgame (2019)",         "genres": "Action|Adventure|Drama|Sci-Fi", "region": "Hollywood"},
    {"movieId": 1000203, "title": "Spider-Man: No Way Home (2021)",   "genres": "Action|Adventure|Sci-Fi",       "region": "Hollywood"},
    {"movieId": 1000204, "title": "Top Gun: Maverick (2022)",         "genres": "Action|Drama",                  "region": "Hollywood"},
    {"movieId": 1000205, "title": "Everything Everywhere All at Once (2022)", "genres": "Action|Adventure|Comedy|Sci-Fi", "region": "Hollywood"},
    {"movieId": 1000206, "title": "Oppenheimer (2023)",               "genres": "Biography|Drama|History|Thriller", "region": "Hollywood"},
    {"movieId": 1000207, "title": "Barbie (2023)",                    "genres": "Adventure|Comedy|Fantasy",      "region": "Hollywood"},
    {"movieId": 1000208, "title": "Dune: Part Two (2024)",            "genres": "Action|Adventure|Drama|Sci-Fi", "region": "Hollywood"},
    {"movieId": 1000209, "title": "Dune (2021)",                      "genres": "Action|Adventure|Drama|Sci-Fi", "region": "Hollywood"},
    {"movieId": 1000210, "title": "The Batman (2022)",                "genres": "Action|Crime|Drama|Mystery",    "region": "Hollywood"},
    {"movieId": 1000211, "title": "Black Panther: Wakanda Forever (2022)", "genres": "Action|Adventure|Drama",  "region": "Hollywood"},
    {"movieId": 1000212, "title": "Guardians of the Galaxy Vol. 3 (2023)", "genres": "Action|Adventure|Comedy", "region": "Hollywood"},
    {"movieId": 1000213, "title": "Mission: Impossible — Dead Reckoning (2023)", "genres": "Action|Adventure|Thriller", "region": "Hollywood"},
    {"movieId": 1000214, "title": "John Wick: Chapter 4 (2023)",      "genres": "Action|Crime|Thriller",        "region": "Hollywood"},
    {"movieId": 1000215, "title": "The Marvels (2023)",               "genres": "Action|Adventure|Sci-Fi",      "region": "Hollywood"},
    {"movieId": 1000216, "title": "Aquaman and the Lost Kingdom (2023)", "genres": "Action|Adventure|Fantasy",  "region": "Hollywood"},
    {"movieId": 1000217, "title": "Deadpool & Wolverine (2024)",      "genres": "Action|Adventure|Comedy|Sci-Fi","region": "Hollywood"},
    {"movieId": 1000218, "title": "Inside Out 2 (2024)",              "genres": "Animation|Comedy|Drama|Family", "region": "Hollywood"},
    {"movieId": 1000219, "title": "Alien: Romulus (2024)",            "genres": "Horror|Sci-Fi|Thriller",       "region": "Hollywood"},
    {"movieId": 1000220, "title": "Twisters (2024)",                  "genres": "Action|Adventure|Drama",       "region": "Hollywood"},
    {"movieId": 1000221, "title": "Gladiator II (2024)",              "genres": "Action|Adventure|Drama",       "region": "Hollywood"},
    {"movieId": 1000222, "title": "Wicked (2024)",                    "genres": "Drama|Fantasy|Musical|Romance", "region": "Hollywood"},
    {"movieId": 1000223, "title": "Moana 2 (2024)",                   "genres": "Adventure|Animation|Comedy|Family", "region": "Hollywood"},
    {"movieId": 1000224, "title": "Kraven the Hunter (2024)",         "genres": "Action|Adventure|Crime",       "region": "Hollywood"},
    {"movieId": 1000225, "title": "Captain America: Brave New World (2025)", "genres": "Action|Adventure|Sci-Fi","region": "Hollywood"},
    # New Hollywood additions
    {"movieId": 1000226, "title": "Joker (2019)",                     "genres": "Crime|Drama|Thriller",          "region": "Hollywood"},
    {"movieId": 1000227, "title": "Joker: Folie à Deux (2024)",       "genres": "Crime|Drama|Musical",           "region": "Hollywood"},
    {"movieId": 1000228, "title": "Parasite (2019)",                  "genres": "Comedy|Drama|Thriller",         "region": "Hollywood"},
    {"movieId": 1000229, "title": "1917 (2019)",                      "genres": "Action|Drama|War",              "region": "Hollywood"},
    {"movieId": 1000230, "title": "Once Upon a Time in Hollywood (2019)", "genres": "Comedy|Crime|Drama",       "region": "Hollywood"},
    {"movieId": 1000231, "title": "Knives Out (2019)",                "genres": "Comedy|Crime|Drama|Mystery",    "region": "Hollywood"},
    {"movieId": 1000232, "title": "Glass Onion (2022)",               "genres": "Comedy|Crime|Drama|Mystery",    "region": "Hollywood"},
    {"movieId": 1000233, "title": "No Time to Die (2021)",            "genres": "Action|Adventure|Thriller",     "region": "Hollywood"},
    {"movieId": 1000234, "title": "The Northman (2022)",              "genres": "Action|Adventure|Drama",        "region": "Hollywood"},
    {"movieId": 1000235, "title": "The Whale (2022)",                 "genres": "Drama",                         "region": "Hollywood"},
    {"movieId": 1000236, "title": "Killers of the Flower Moon (2023)","genres": "Crime|Drama|History|Mystery",   "region": "Hollywood"},
    {"movieId": 1000237, "title": "Poor Things (2023)",               "genres": "Comedy|Drama|Romance|Sci-Fi",   "region": "Hollywood"},
    {"movieId": 1000238, "title": "The Holdovers (2023)",             "genres": "Comedy|Drama",                  "region": "Hollywood"},
    {"movieId": 1000239, "title": "Past Lives (2023)",                "genres": "Drama|Romance",                 "region": "Hollywood"},
    {"movieId": 1000240, "title": "Anatomy of a Fall (2023)",         "genres": "Crime|Drama|Mystery|Thriller",  "region": "Hollywood"},
    {"movieId": 1000241, "title": "The Zone of Interest (2023)",      "genres": "Drama|History|War",             "region": "Hollywood"},
    {"movieId": 1000242, "title": "Wonka (2023)",                     "genres": "Adventure|Comedy|Family|Fantasy","region": "Hollywood"},
    {"movieId": 1000243, "title": "A Quiet Place: Day One (2024)",    "genres": "Drama|Horror|Sci-Fi|Thriller",  "region": "Hollywood"},
    {"movieId": 1000244, "title": "Furiosa: A Mad Max Saga (2024)",   "genres": "Action|Adventure|Sci-Fi",       "region": "Hollywood"},
    {"movieId": 1000245, "title": "Challengers (2024)",               "genres": "Drama|Romance|Sport",           "region": "Hollywood"},
    {"movieId": 1000246, "title": "Civil War (2024)",                 "genres": "Action|Drama|Thriller",         "region": "Hollywood"},
    {"movieId": 1000247, "title": "The Fall Guy (2024)",              "genres": "Action|Comedy|Romance",         "region": "Hollywood"},
    {"movieId": 1000248, "title": "Despicable Me 4 (2024)",           "genres": "Animation|Comedy|Family",       "region": "Hollywood"},
    {"movieId": 1000249, "title": "Beetlejuice Beetlejuice (2024)",   "genres": "Comedy|Fantasy|Horror",         "region": "Hollywood"},
    {"movieId": 1000250, "title": "Smile 2 (2024)",                   "genres": "Horror|Mystery|Thriller",       "region": "Hollywood"},
    {"movieId": 1000251, "title": "Venom: The Last Dance (2024)",     "genres": "Action|Adventure|Sci-Fi",       "region": "Hollywood"},
    {"movieId": 1000252, "title": "The Wild Robot (2024)",            "genres": "Adventure|Animation|Drama|Sci-Fi","region": "Hollywood"},
    {"movieId": 1000253, "title": "Conclave (2024)",                  "genres": "Drama|Mystery|Thriller",        "region": "Hollywood"},
    {"movieId": 1000254, "title": "Nosferatu (2024)",                 "genres": "Drama|Fantasy|Horror",          "region": "Hollywood"},
    {"movieId": 1000255, "title": "Anora (2024)",                     "genres": "Comedy|Drama|Romance",          "region": "Hollywood"},
]
