"""
Supplementary curated movies catalog — Bollywood, South Indian & modern Hollywood.
These movies are injected alongside MovieLens data.
IDs start at 1,000,000 to avoid collisions with MovieLens IDs.
Genres use the same pipe-delimited format as MovieLens.
"""

CUSTOM_MOVIES = [
    # ── Bollywood / Hindi ────────────────────────────────────────────────────
    {"movieId": 1000001, "title": "3 Idiots (2009)",                  "genres": "Comedy|Drama",                  "region": "Bollywood"},
    {"movieId": 1000002, "title": "Dangal (2016)",                    "genres": "Drama|Sport",                    "region": "Bollywood"},
    {"movieId": 1000003, "title": "PK (2014)",                        "genres": "Comedy|Drama|Sci-Fi",            "region": "Bollywood"},
    {"movieId": 1000004, "title": "Lagaan (2001)",                    "genres": "Drama|Sport",                    "region": "Bollywood"},
    {"movieId": 1000005, "title": "Barfi! (2012)",                    "genres": "Comedy|Drama|Romance",           "region": "Bollywood"},
    {"movieId": 1000006, "title": "Dil Chahta Hai (2001)",            "genres": "Comedy|Drama|Romance",           "region": "Bollywood"},
    {"movieId": 1000007, "title": "Zindagi Na Milegi Dobara (2011)",  "genres": "Adventure|Comedy|Drama",         "region": "Bollywood"},
    {"movieId": 1000008, "title": "Taare Zameen Par (2007)",          "genres": "Drama",                         "region": "Bollywood"},
    {"movieId": 1000009, "title": "Queen (2014)",                     "genres": "Drama|Romance",                  "region": "Bollywood"},
    {"movieId": 1000010, "title": "Andhadhun (2018)",                 "genres": "Crime|Mystery|Thriller",         "region": "Bollywood"},
    {"movieId": 1000011, "title": "Gangs of Wasseypur (2012)",        "genres": "Action|Crime|Drama",             "region": "Bollywood"},
    {"movieId": 1000012, "title": "Drishyam (2015)",                  "genres": "Crime|Drama|Mystery|Thriller",   "region": "Bollywood"},
    {"movieId": 1000013, "title": "KB (Kabir Singh) (2019)",          "genres": "Drama|Romance",                  "region": "Bollywood"},
    {"movieId": 1000014, "title": "War (2019)",                       "genres": "Action|Thriller",                "region": "Bollywood"},
    {"movieId": 1000015, "title": "Pathaan (2023)",                   "genres": "Action|Adventure|Thriller",      "region": "Bollywood"},
    {"movieId": 1000016, "title": "Jawan (2023)",                     "genres": "Action|Drama|Thriller",          "region": "Bollywood"},
    {"movieId": 1000017, "title": "Animal (2023)",                    "genres": "Action|Crime|Drama",             "region": "Bollywood"},
    {"movieId": 1000018, "title": "Tumbbad (2018)",                   "genres": "Fantasy|Horror|Mystery",         "region": "Bollywood"},
    {"movieId": 1000019, "title": "Article 15 (2019)",                "genres": "Crime|Drama|Mystery",            "region": "Bollywood"},
    {"movieId": 1000020, "title": "Shershaah (2021)",                 "genres": "Action|Biography|Drama|War",     "region": "Bollywood"},
    {"movieId": 1000021, "title": "83 (2021)",                        "genres": "Biography|Drama|Sport",          "region": "Bollywood"},
    {"movieId": 1000022, "title": "Brahmastra (2022)",                "genres": "Action|Adventure|Fantasy",       "region": "Bollywood"},
    {"movieId": 1000023, "title": "Kho Gaye Hum Kahan (2023)",        "genres": "Comedy|Drama|Romance",           "region": "Bollywood"},
    {"movieId": 1000024, "title": "Swades (2004)",                    "genres": "Drama|Romance",                  "region": "Bollywood"},
    {"movieId": 1000025, "title": "Band Baaja Baaraat (2010)",        "genres": "Comedy|Romance",                 "region": "Bollywood"},

    # ── South Indian ─────────────────────────────────────────────────────────
    {"movieId": 1000101, "title": "Baahubali: The Beginning (2015)",  "genres": "Action|Adventure|Fantasy|Drama", "region": "South Indian"},
    {"movieId": 1000102, "title": "Baahubali 2: The Conclusion (2017)","genres": "Action|Adventure|Fantasy|Drama","region": "South Indian"},
    {"movieId": 1000103, "title": "RRR (2022)",                       "genres": "Action|Adventure|Drama",         "region": "South Indian"},
    {"movieId": 1000104, "title": "KGF: Chapter 1 (2018)",            "genres": "Action|Crime|Drama",             "region": "South Indian"},
    {"movieId": 1000105, "title": "KGF: Chapter 2 (2022)",            "genres": "Action|Crime|Drama",             "region": "South Indian"},
    {"movieId": 1000106, "title": "Vikram (2022)",                    "genres": "Action|Crime|Thriller",          "region": "South Indian"},
    {"movieId": 1000107, "title": "Pushpa: The Rise (2021)",          "genres": "Action|Crime|Drama",             "region": "South Indian"},
    {"movieId": 1000108, "title": "Pushpa 2: The Rule (2024)",        "genres": "Action|Crime|Drama",             "region": "South Indian"},
    {"movieId": 1000109, "title": "Kantara (2022)",                   "genres": "Action|Drama|Mystery|Thriller",  "region": "South Indian"},
    {"movieId": 1000110, "title": "Varisu (2023)",                    "genres": "Action|Drama|Family",            "region": "South Indian"},
    {"movieId": 1000111, "title": "Dasara (2023)",                    "genres": "Action|Drama",                   "region": "South Indian"},
    {"movieId": 1000112, "title": "Leo (2023)",                       "genres": "Action|Crime|Thriller",          "region": "South Indian"},
    {"movieId": 1000113, "title": "Jailer (2023)",                    "genres": "Action|Comedy|Drama",            "region": "South Indian"},
    {"movieId": 1000114, "title": "Salaar (2023)",                    "genres": "Action|Crime|Drama",             "region": "South Indian"},
    {"movieId": 1000115, "title": "Maharaja (2024)",                  "genres": "Action|Crime|Thriller",          "region": "South Indian"},
    {"movieId": 1000116, "title": "Vikram Vedha (2022)",              "genres": "Action|Crime|Drama|Thriller",    "region": "South Indian"},
    {"movieId": 1000117, "title": "Soorarai Pottru (2020)",           "genres": "Biography|Drama",                "region": "South Indian"},
    {"movieId": 1000118, "title": "Jai Bhim (2021)",                  "genres": "Crime|Drama|Mystery",            "region": "South Indian"},
    {"movieId": 1000119, "title": "2.0 (2018)",                       "genres": "Action|Sci-Fi|Thriller",         "region": "South Indian"},
    {"movieId": 1000120, "title": "Kalki 2898 AD (2024)",             "genres": "Action|Adventure|Fantasy|Sci-Fi","region": "South Indian"},
    {"movieId": 1000121, "title": "Devara (2024)",                    "genres": "Action|Crime|Drama",             "region": "South Indian"},
    {"movieId": 1000122, "title": "Kanguva (2024)",                   "genres": "Action|Adventure|Fantasy",       "region": "South Indian"},
    {"movieId": 1000123, "title": "Nayakan (1987)",                   "genres": "Crime|Drama|Thriller",           "region": "South Indian"},
    {"movieId": 1000124, "title": "Drishyam 2 (2021)",                "genres": "Crime|Drama|Mystery|Thriller",   "region": "South Indian"},
    {"movieId": 1000125, "title": "Lucifer (2019)",                   "genres": "Action|Crime|Drama|Thriller",    "region": "South Indian"},

    # ── Modern Hollywood (2018-2025) ─────────────────────────────────────────
    {"movieId": 1000201, "title": "Avengers: Infinity War (2018)",    "genres": "Action|Adventure|Sci-Fi",       "region": "Hollywood"},
    {"movieId": 1000202, "title": "Avengers: Endgame (2019)",         "genres": "Action|Adventure|Drama|Sci-Fi", "region": "Hollywood"},
    {"movieId": 1000203, "title": "Spider-Man: No Way Home (2021)",   "genres": "Action|Adventure|Sci-Fi",       "region": "Hollywood"},
    {"movieId": 1000204, "title": "Top Gun: Maverick (2022)",         "genres": "Action|Drama",                  "region": "Hollywood"},
    {"movieId": 1000205, "title": "Everything Everywhere All at Once (2022)", "genres": "Action|Adventure|Comedy|Sci-Fi", "region": "Hollywood"},
    {"movieId": 1000206, "title": "Oppenheimer (2023)",               "genres": "Biography|Drama|History|Thriller", "region": "Hollywood"},
    {"movieId": 1000207, "title": "Barbie (2023)",                    "genres": "Adventure|Comedy|Fantasy",      "region": "Hollywood"},
    {"movieId": 1000208, "title": "Dune: Part Two (2024)",            "genres": "Action|Adventure|Drama|Sci-Fi", "region": "Hollywood"},
    {"movieId": 1000209, "title": "Dune (2021)",                      "genres": "Action|Adventure|Drama|Sci-Fi", "region": "Hollywood"},
    {"movieId": 1000210, "title": "The Batman (2022)",                "genres": "Action|Crime|Drama|Mystery",    "region": "Hollywood"},
    {"movieId": 1000211, "title": "Black Panther: Wakanda Forever (2022)", "genres": "Action|Adventure|Drama",  "region": "Hollywood"},
    {"movieId": 1000212, "title": "Guardians of the Galaxy Vol. 3 (2023)", "genres": "Action|Adventure|Comedy", "region": "Hollywood"},
    {"movieId": 1000213, "title": "Mission: Impossible — Dead Reckoning (2023)", "genres": "Action|Adventure|Thriller", "region": "Hollywood"},
    {"movieId": 1000214, "title": "John Wick: Chapter 4 (2023)",      "genres": "Action|Crime|Thriller",        "region": "Hollywood"},
    {"movieId": 1000215, "title": "The Marvels (2023)",               "genres": "Action|Adventure|Sci-Fi",      "region": "Hollywood"},
    {"movieId": 1000216, "title": "Aquaman and the Lost Kingdom (2023)", "genres": "Action|Adventure|Fantasy",  "region": "Hollywood"},
    {"movieId": 1000217, "title": "Deadpool & Wolverine (2024)",      "genres": "Action|Adventure|Comedy|Sci-Fi","region": "Hollywood"},
    {"movieId": 1000218, "title": "Inside Out 2 (2024)",              "genres": "Animation|Comedy|Drama|Family", "region": "Hollywood"},
    {"movieId": 1000219, "title": "Alien: Romulus (2024)",            "genres": "Horror|Sci-Fi|Thriller",       "region": "Hollywood"},
    {"movieId": 1000220, "title": "Twisters (2024)",                  "genres": "Action|Adventure|Drama",       "region": "Hollywood"},
    {"movieId": 1000221, "title": "Gladiator II (2024)",              "genres": "Action|Adventure|Drama",       "region": "Hollywood"},
    {"movieId": 1000222, "title": "Wicked (2024)",                    "genres": "Drama|Fantasy|Musical|Romance", "region": "Hollywood"},
    {"movieId": 1000223, "title": "Moana 2 (2024)",                   "genres": "Adventure|Animation|Comedy|Family", "region": "Hollywood"},
    {"movieId": 1000224, "title": "Kraven the Hunter (2024)",         "genres": "Action|Adventure|Crime",       "region": "Hollywood"},
    {"movieId": 1000225, "title": "Captain America: Brave New World (2025)", "genres": "Action|Adventure|Sci-Fi","region": "Hollywood"},
]
